# Generated by Django 2.0.2 on 2019-06-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_mensaje_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='agente_usuario',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
