# Generated by Django 2.0.2 on 2019-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_auto_20190608_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_usuario', models.CharField(max_length=250, null=True)),
                ('ip', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'accesos',
            },
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='agente_usuario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='ip',
        ),
    ]
